### ISSUE TITLE
Rename the tool?

### ISSUE THREAD

**Issue by omitar** [oasislabs/oasis-cli#103]
## Details

There is already a command line tool called [oasis](https://packages.ubuntu.com/disco/oasis). Ubuntu suggests that if you try to run `oasis` without installing anything.

Maybe rename this tool to something else?

**Comment by nhynes** [comment]
Let’s reopen this if someone actually encounters this issue.

**Comment by omitar** [comment]
What do you mean? I encountered the issue?
