### ISSUE TITLE
Provide a way to install the Rust the Oasis CLI needs with the install script

### ISSUE THREAD

**Issue by omitar** [oasislabs/oasis-cli#110]
It looks like if Rust is already installed on the system, the install script does not install anything Rust related. Which means that if the version on the system does not match what Oasis needs, you get an error like:

```
error: toolchain 'nightly-2019-08-01-x86_64-unknown-linux-gnu' is not installed
```

I suggest that or Oasis installs everything necessary even in this case (unless `--no-rust` is provided), or that a new switch is added, something like `--force-rust`, to force Rust installation with all correct versions of dependencies.

**Comment by nhynes** [comment]
this has been resolved
