### ISSUE TITLE
Provide a way for a fixed version of Oasis SDK to be installed using https://get.oasis.dev

### ISSUE THREAD

**Issue by omitar** [oasislabs/oasis-cli#115]
Because it seems it is always installing the latest version, which breaks then my service despite my service having a fixed `Cargo.lock`, which makes CI flaky. Ideally, I would like to freeze all dependencies, including Oasis SDK.

**Comment by nhynes** [comment]
resolved by #105

**Comment by omitar** [comment]
Please close the issue once this is available. That is still a PR, no?
