### ISSUE TITLE
Updating the toolchain doesn't update profile fields

### ISSUE THREAD

**Issue by david-yan** [oasislabs/oasis-cli#129]
Running `oasis set-toolchain latest` doesn't update the fields in the profile. This leads to unexplained and undocumented errors such as 
```error: `profile.local` is missing field: `gateway`.``` 
when trying to deploy. We should either make sure that the update updates the fields, or there's documentation somewhere explaining what to do about this error.

**Comment by nhynes** [comment]
This was a one time breaking change. If we ever do this again (I hope we don't), we'll update the fields.
