### ISSUE TITLE
`oasis build` doesn't find project

### ISSUE THREAD

**Issue by rebekahkim** [oasislabs/oasis-cli#137]
**Description of the bug**
The oasis CLI doesn't find project even when Cargo file present

**Steps to reproduce**
1. unzip tarball from https://oasis-labs.slack.com/archives/CHG7KV2RH/p1569710854165400?thread_ts=1569679075.141700&cid=CHG7KV2RH
2. `oasis build` in `service
3. See error
```
error: no project in `/Users/Kim/ballot/service` or any parent directory
```

**Expected behavior**
Builds service

**Environment**
 - OS: macOS Mojave
 - Versions of relevant software and tools: Oasis CLI for both md5 = {5f790a1f60da0adbcfd5193dcf5e44c5, 950fa5f24095d48d943ee854fff8ee72} (latest, unstable)

cc: @ennsharma

**Comment by nhynes** [comment]
The workspace is a git repo. You'll need to `git init` somewhere for oasis-cli to work.
