### ISSUE TITLE
Initial web deployment

### ISSUE THREAD

**Issue by willscott** [oasislabs/oasis-cli#30]
As a path-of-least-resistance, a proposal for how an `oasis deploy` would work:
1. the cli takes the .wasm and either wraps it as jsonp (so accessible from a file://... url) or wraps it directly in an html template.
2. The cli then calls `open` (mac) or `xdg-open` (linux) to open your default browser to the generated html page.
3. the page uses oasis-client to attempt a deploy against the developer gateway.
3a. the user has dashboard cookies, and so the developer gateway can authenticate + sign the request. it deploys :tada:
3b. the user does not have dashboard cookies. the page displays a message that they are not logged in, with a 'retry' button and a link to log in to dashboard.
4. the page provides a deep link to the dashboard deployment page for the resulting service.

**Comment by nhynes** [comment]
Resolved by #91 (at least for now)
