### ISSUE TITLE
`oasis test --help` gives potentially confusing description

### ISSUE THREAD

**Issue by armaniferrante** [oasislabs/oasis-cli#71]
`Run integration tests against a simulated Oasis runtime.` could be interpreted as running application integration tests (e.g., jest or mocha) against a ganache like in-memory chain, i.e., `oasis-chain`.

This is particularly the case when reading through tutorials that use everything together.

It might be more clear to `s/integration/Cargo`.

Feel free to close or come up with better wording.

**Comment by nhynes** [comment]
Resolved in #91
