### ISSUE TITLE
`oasis login`

### ISSUE THREAD

**Issue by nhynes** [oasislabs/oasis-cli#96]
Obtain an API key from the developer gateway that can be used by the Rust client to deploy services.

**Comment by eauge** [comment]
- Dashboard exposes private key and hash of the private key. The hash of the private key is exposed as an API Token.
 - Docs to tell user to store api key in the oasis-cli configuration file
 - `oasis login` tells user to go to dashboard to retrieve API Token, and user can paste API Key on the CLI
 - For deploy, CLI will send API Token to developer-gateway
 - Developer-gateway needs to get the API Token from the request and use it with the dashboard to verify the request.
